---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: grok-exporter_PR
  image: plugins/docker
  settings:
    dry_run: true
    registry: docker.io
    repo: ciscocx/grok-exporter
  when:
    event:
    - pull_request
    ref:
    - refs/heads/master
    - refs/tags/*

- name: grok-exporter
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: docker.io
    repo: ciscocx/grok-exporter
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/master
    - refs/tags/*

- name: send_notification
  image: plugins/slack
  settings:
    channel: drone-ci
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-64.png
    username: Drone CI
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - failure

---
kind: signature
hmac: 919f6d77a6210bfcd1ce5dc22bd955f4bd894ae220710208925d622df0a51dbd

...
